config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('post/', include('post.urls')),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('join', views.join, name='join'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('check/userid', views.check_userid, name='check_userid'),
    path('check/nickname', views.check_nickname, name='check_nickname'),
    path('confirm_password', views.confirmPassword, name='confirm_password'),
    path('update_user', views.updateUser, name='update_user'),
]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('<str:model>/write/', views.write, name='write'),
    path('<str:model>/update/<int:pk>/', views.update, name='update'),
    path('<str:model>/list/', views.list, name='list'),
    path('<str:model>/detail/<int:pk>/', views.detail, name='detail'),
    path('<str:model>/delete/<int:pk>/', views.delete, name='delete'),
    path('<str:model>/export/', views.export, name='export'),
    path('check/<str:model>/<str:field_name>/<str:ele_id>/', views.check, name='check'),
    path('search/<str:model>/<str:field_name>/', views.search, name='search'),
    path('select/<str:model>/<int:id>/', views.select, name='select'),

    path('<str:model>/<int:id>/answer/write/', views.writeAnswer, name='answer_write'),
    path('answer/detail/<int:pk>/', views.detail, name='answer_detail'),
    path('answer/update/<int:pk>/', views.detail, name='answer_update'),
    path('answer/delete/<int:pk>/', views.detail, name='answer_delete'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser)
from django.utils import timezone
from choice.choices import get_choices
from django.db.models import Q

class SendEmail(AbstractBaseUser):
    email = models.EmailField(max_length=100)

    password = models.CharField(max_length=100)

    USERNAME_FIELD = 'email'

class UserManager(BaseUserManager):
    def create_user(self,userid, name, nickname ,email, password=None):
        if not userid:
            raise ValueError('Users must have an userid')

        user = self.model(
            userid = userid,
            user_name = name,
            nickname = nickname,
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, userid, user_name , nickname, email, password):
        user = self.create_user(
            userid,
            user_name,
            nickname,
            email,
            password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    userid = models.CharField(
        verbose_name='아이디',
        max_length=50,
        unique=True,
    )

    user_name = models.CharField(
        verbose_name='이름',
        max_length=50,
    )

    email = models.EmailField(
        verbose_name='이메일',
        max_length=255,
    )

    #email_password = models.CharField(max_length=100, null=True, blank=True)

    nickname = models.CharField(
        verbose_name='닉네임',
        max_length=30,
        unique=True
    )
    date_joined = models.DateTimeField(
        verbose_name='가입일자',
        default=timezone.now
    )
    password = models.CharField(
        verbose_name='비밀번호',
        max_length=255
    )
    is_admin = models.BooleanField(default=False)

    send_email = models.ForeignKey(SendEmail, on_delete=models.CASCADE, null=True, blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'userid'
    REQUIRED_FIELDS = ['nickname', ]

    class Meta:
        ordering = ('-date_joined',)

    def __str__(self):
        return self.user_name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin



class Address(models.Model):
    address = models.CharField(max_length=200)

    address_old = models.CharField(max_length=200, null=True, blank=True)

    detail = models.CharField(max_length=100, null=True, blank=True)

    zip_code = models.CharField(max_length=20, null=True, blank=True)

    note = models.CharField(max_length=100, null=True, blank=True)

    location = models.CharField(max_length=20, choices=get_choices('location'))

    overseas_address = models.CharField(max_length=200, null=True, blank=True)


class Security(models.Model):
    contract = models.CharField(max_length=50, null=True, blank=True, choices=get_choices('contract'))

    block_permis = models.CharField(max_length=50, null=True, blank=True, choices=get_choices('block_permis'))

    send_date = models.DateField(null=True, blank=True)

    interlock_date = models.DateField(null=True, blank=True)

    serial = models.CharField(max_length=100, null=True, blank=True)

    expiry_date = models.DateField(null=True, blank=True)

    firmware = models.CharField(max_length=50, null=True, blank=True)

    equipment_class = models.CharField(max_length=50, null=True, blank=True, choices=get_choices('equipment_class'))

    ownership = models.CharField(max_length=50, null=True, blank=True, choices=get_choices('ownership'))

    access_permis = models.CharField(max_length=50, null=True, blank=True, choices=get_choices('access_permis'))

    termination_date = models.DateField(null=True, blank=True)

    termination_reason = models.CharField(max_length=50, null=True, blank=True)

    ips_rule = models.CharField(max_length=30, null=True, blank=True, choices=get_choices('ips_check'))

    sys_log = models.CharField(max_length=30, null=True, blank=True, choices=get_choices('ips_check'))

    icmp = models.CharField(max_length=30, null=True, blank=True, choices=get_choices('ips_check'))

    snmp = models.CharField(max_length=30, null=True, blank=True, choices=get_choices('ips_check'))

    snmp_sub = models.CharField(max_length=30, null=True, blank=True, choices=get_choices('snmp_sub'))

    etc = models.CharField(max_length=255, null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)

    updated = models.DateTimeField(auto_now=True)

class Internal(models.Model):
    contract = models.CharField(max_length=50, null=True, blank=True, choices=get_choices('contract'))

    apply_n = models.IntegerField(null=True, blank=True)

    interlock_date = models.DateField(null=True, blank=True)

    ip = models.CharField(max_length=100, null=True, blank=True)

    termination_date = models.DateField(null=True, blank=True)

    termination_reason = models.CharField(max_length=50, null=True, blank=True)

    etc = models.CharField(max_length=255, null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)

    updated = models.DateTimeField(auto_now=True)

class Virus(models.Model):
    contract = models.CharField(max_length=50, null=True, blank=True, choices=get_choices('contract'))

    apply_n = models.IntegerField(null=True, blank=True)

    interlock_date = models.DateField(null=True, blank=True)

    termination_date = models.DateField(null=True, blank=True)

    termination_reason = models.CharField(max_length=50, null=True, blank=True)

    etc = models.CharField(max_length=255, null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)

    updated = models.DateTimeField(auto_now=True)

class Ransomware(models.Model):
    contract = models.CharField(max_length=50, null=True, blank=True, choices=get_choices('contract'))

    apply_n = models.IntegerField(null=True, blank=True)

    interlock_date = models.DateField(null=True, blank=True)

    termination_date = models.DateField(null=True, blank=True)

    termination_reason = models.CharField(max_length=50, null=True, blank=True)

    etc = models.CharField(max_length=255, null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)

    updated = models.DateTimeField(auto_now=True)

class Company(models.Model):
    name = models.CharField(max_length=50, verbose_name='업체명')

    tenant = models.BooleanField(blank=True, default=False, verbose_name='입주기업')

    ss_security = models.CharField(max_length=20, choices=get_choices('service_state'), verbose_name='서비스현황-보안관제')

    ss_internal = models.CharField(max_length=20, choices=get_choices('service_state'), verbose_name='서비스현황-내부정보')

    ss_virus = models.CharField(max_length=20, choices=get_choices('service_state'), verbose_name='서비스현황-악성코드')

    ss_ransomware = models.CharField(max_length=20, choices=get_choices('service_state'), verbose_name='서비스현황-랜섬웨어')

    im_state = models.CharField(max_length=20, blank=True, default='0000')

    business_type = models.CharField(max_length=50, choices=get_choices('business_type'), verbose_name='사업자유형')

    business_etc = models.CharField(max_length=50, blank=True, null=True)

    business_uptae = models.CharField(max_length=50, choices=get_choices('business_uptae'), verbose_name='업태')

    business_class = models.CharField(max_length=50, choices=get_choices('business_class'), verbose_name='업종')

    join_path = models.CharField(max_length=50, choices=get_choices('join_path'), verbose_name='가입경로')

    top_name = models.CharField(max_length=50, verbose_name='대표자명')

    #top_email = models.EmailField()

    homepage = models.CharField(max_length=100, null=True, blank=True, verbose_name='홈페이지')

    business_n = models.IntegerField(verbose_name='사업자번호')

    address = models.ForeignKey(Address, on_delete=models.DO_NOTHING, related_name='company_address')

    #install_address = models.ForeignKey(Address, on_delete=models.DO_NOTHING, related_name='install_address')

    operation_etc = models.CharField(max_length=50, null=True, blank=True)

    large_etc = models.CharField(max_length=50, null=True, blank=True)

    major_etc = models.CharField(max_length=50, null=True, blank=True)

    closed_etc = models.CharField(max_length=50, null=True, blank=True)

    defense_etc = models.CharField(max_length=50, null=True, blank=True)

    smart_etc = models.CharField(max_length=50, null=True, blank=True)

    large_scale = models.CharField(max_length=50, null=True, blank=True, choices=get_choices('large_scale'))

    major_partner = models.CharField(max_length=50, null=True, blank=True, choices=get_choices('major_partner'))

    closed_net = models.CharField(max_length=50, null=True, blank=True, choices=get_choices('closed_net'))

    defense_industry = models.CharField(max_length=50, null=True, blank=True, choices=get_choices('defense_industry'))

    smart_factory = models.CharField(max_length=50, null=True, blank=True, choices=get_choices('smart_factory'))

    manager_m_name = models.CharField(max_length=50, verbose_name='(정)-이름')

    manager_m_depart = models.CharField(max_length=50)

    manager_m_phone = models.IntegerField()

    manager_m_cphone = models.IntegerField()

    manager_m_email = models.EmailField()

    manager_s_name = models.CharField(max_length=50, null=True, blank=True)

    manager_s_depart = models.CharField(max_length=50, null=True, blank=True)

    manager_s_phone = models.IntegerField(null=True, blank=True)

    manager_s_cphone = models.IntegerField(null=True, blank=True)

    manager_s_email = models.EmailField(null=True, blank=True)

    manager_f_name = models.CharField(max_length=50, null=True, blank=True)

    manager_f_depart = models.CharField(max_length=50, null=True, blank=True)

    manager_f_phone = models.IntegerField(null=True, blank=True)

post/all_forms/calendar/forms.py
from django import forms
from post.models import Schedule, Attendance
from post.my_def import to_date_widget

class ScheduleForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ScheduleForm, self).__init__(*args, **kwargs)
        to_date_widget(self.fields)

    class Meta:
        model = Schedule
        exclude = ('user','views')

class AttendanceForm(forms.ModelForm):
    class Meta:
        model = Attendance
        exclude = ('user', )

post/all_views/calendar/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse, HttpResponse
import datetime, calendar
from post.models import Schedule, Attendance, Comment
from post.all_forms.calendar.forms import ScheduleForm, AttendanceForm
from django.contrib.auth.decorators import login_required
import datetime
from django.db.models import Q
from post.my_def import delete_object


@login_required
def writeSchedule(request):
    if request.method == 'POST':
        form = ScheduleForm(request.POST, request.FILES)
        if form.is_valid():
            obj =form.save(commit=False)
            obj.user = request.user
            obj.save()
            return HttpResponseRedirect(reverse("post:list",args=['calendar']))
    else:
        form = ScheduleForm()
    return render(request, 'post/calendar/write.html', {'form':form})

def deleteSchedule(request, id):
    delete_object(Schedule, id)
    return HttpResponseRedirect(reverse('post:list', args=['calendar']))

@login_required
def writeAttendance(request):
    today = datetime.datetime.today()
    success = False
    if request.method == 'POST':
        form = AttendanceForm(request.POST, request.FILES, label_suffix="")
        if form.is_valid():
            obj =form.save(commit=False)
            obj.user = request.user
            obj.save()
            success = today.strftime('%H:%M:%S')
    else:
        form = AttendanceForm(label_suffix="")
    return render(request, 'post/calendar/attendance_write.html', {'form':form, 'success':success})

@login_required
def updateSchedule(request, id):
    instance = Schedule.objects.get(id=id)
    if request.method == 'POST':
        form = ScheduleForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse(('post:list'), args=['calendar']))
    else:
        form = ScheduleForm(instance=instance)
    return render(request, 'post/calendar/write.html', {'form':form})

@login_required
def updateAttendance(request, id):
    today = datetime.datetime.today()
    success = False
    instance = Attendance.objects.get(id=id)
    if request.method == 'POST':
        form = AttendanceForm(request.POST, instance=instance, label_suffix="")
        if form.is_valid():
            form.save()
            success = today.strftime('%H:%M:%S')
    else:
        form = AttendanceForm(instance=instance, label_suffix="")
    return render(request, 'post/calendar/attendance_write.html', {'form':form, 'success':success})

def listCalendar(request):
    today = datetime.datetime.today()
    default_GET = '?year=%s&month=%s'%(today.year, today.month)

    if not request.GET:
        return set_default(default_GET)

    else:
        try:
            year = int(request.GET['year'])
            month = int(request.GET['month'])
            if month == 13:
                return set_default(('?year=%s&month=%s'%(year+1, 1)))
            if month == 0:
                return set_default(('?year=%s&month=%s'%(year-1, 12)))

        except:
            return set_default(default_GET)

        days = get_content_month(year,month)
        today = Schedule.get_today()
        return render(request, 'post/calendar/list.html', {'days': days, 'today': today})

def detailSchedule(request, id):
    model = Schedule

    object = model.objects.get(id=id)
    comment = Comment.objects.filter(model_name=model.__name__, model_pk=id)

    content = {
        'object': object,
        'comment': comment,
    }
    return render(request, 'post/calendar/detail.html', content)


def set_default(default_GET):
    redirect = reverse('post:list', args=['calendar']) + default_GET
    return HttpResponseRedirect(redirect)

def get_content_month(year, month):
    cal = calendar.Calendar(firstweekday=6)
    days = cal.monthdayscalendar(year, month)
    new_days = []
    for week in days:
        cur_week = []
        for day in week:
            if not day:
                schedule = None
                attendancd = None
            else:
                date = datetime.date(year, month, day)
                Q1 = Q(start_date__lte=date)
                Q2 = Q(end_date__gte=date)
                schedule = Schedule.objects.filter(Q1 & Q2).order_by('start_date')
                attendancd = Attendance.objects.filter(attendance_date=date)

            content = {'day':day , 'schedule': schedule, 'attendance': attendancd}
            cur_week.append(content)

        new_days.append(cur_week)

    return new_days

post/all_views/check/views.py
from django.shortcuts import render
from main.models import Company, User
from post.models import DetectionPattern

def check(request, model,field_name, ele_id):
    success = False
    verbose_name = eval("%s._meta.get_field('%s').verbose_name"%(model,field_name))
    confirm_data = ""
    if request.method == 'POST':
        confirm_data = request.POST['confirm_data']
        if not eval("%s.objects.filter(%s='%s')"%(model,field_name,confirm_data)):
            success = True
    content = {
        'verbose_name':verbose_name,
        'confirm_data':confirm_data,
        'success':success,
        'ele_id':ele_id,
    }
    return render(request, 'post/check/check.html', content)

post/templates/post/companyrecord/detail.html
{% extends 'base.html' %}

{% block content %}
{% load post_extras %}
<style>
    table {width:100%;}
    td {height:70px;}
    .c1, .c3, .c5 {
        width:140px;
        background-color: #EFFBFB;
        text-align: center;
     }
     .tb {margin-top:40px;}
     .btn_div *{margin:20px;}
     .btn_div {text-align:center;}
</style>
<h3>[{{object.division}}]{{object.title}}</h3>


<div class="tb">
    <h5>업무 처리 현황</h5>
    <table border="1">
        <tr>
            <td class="c1">수혜기업명</td>
            <td class="c2">{{object.company.name}}</td>
            <td class="c3">업무처리 상태</td>
            <td class="c4">{{object.process_state}}</td>
        </tr>

        <tr>
            <td class="c1">업무구분</td>
            <td class="c2">{{object.division}}</td>
            <td class="c3">사업자 유형</td>
            <td class="c4">{{object.company.business_type}}</td>
        </tr>

        <tr>
            <td class="c1">처리방법</td>
            <td class="c2">{{object.process_method}} {{object.process_method_etc | not_none}}</td>
            <td class="c3">접수/발생 일시</td>
            <td class="c4">{{object.occurr_date}}</td>
        </tr>
    </table>
</div>

<div class="tb">
    <h5>업무 처리 관련 담당자 정보</h5>
    <table border="1">
        <thead>
        <tr>
            <td class="c1">이름</td>
            <td class="c1">회사전화</td>
            <td class="c1">핸드폰</td>
            <td class="c1">E-mail</td>
        </tr>
        </thead>
        <tbody>
        {% if object.visible_m %}
        <tr>
            <td>{{object.company.manager_m_name}}</td>
            <td>{{object.company.manager_m_cphone}}</td>
            <td>{{object.company.manager_m_phone}}</td>
            <td>{{object.company.manager_m_email}}</td>
        </tr>
        {% endif %}

        {% if object.visible_s %}
        <tr>
            <td>{{object.company.manager_s_name}}</td>
            <td>{{object.company.manager_s_cphone}}</td>
            <td>{{object.company.manager_s_phone}}</td>
            <td>{{object.company.manager_s_email}}</td>
        </tr>
        {% endif %}

        {% if object.visible_e %}
        <tr>
            <td>{{object.manager_e_name}}</td>
            <td>{{object.manager_e_cphone}}</td>
            <td>{{object.manager_e_phone}}</td>
            <td>{{object.manager_e_email}}</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>

<div class="tb">
    <h5>업무 처리 내용 및 관련 사항</h5>
    <table border="1">
        <tr>
            <td>{{object.title}}</td>
        </tr>
        <tr>
            <td>{{object.content}}</td>
        </tr>
    </table>
</div>

<div class="tb">
<div class="btn_div">
    {% if pre_obj %}
    <a href="#" onclick="location.href = '{% url 'post:detail' 'companyrecord' pre_obj.id %}'"><button type="button">이전글</button></a>
    {% endif %}
    {% if next_obj %}
    <a href="#" onclick="location.href = '{% url 'post:detail' 'companyrecord' next_obj.id %}'"><button type="button">다음글</button></a>
    {% endif %}
    <a href="#" onclick="location.href = '{{uri}}'"><button type="button">목록으로</button></a>
    {% if request.user.id == object.user.id %}
    <a href="#" onclick="location.href = ' {% url 'post:update' 'companyrecord' object.id %} '"><button type="button">수정하기</button></a>
    <a href="#" onclick="location.href = ' {% url 'post:delete' 'companyrecord' object.id %} '"><button type="button">삭제</button></a>
    {% endif %}
    <a href="#" onclick="location.href = ' {% url 'post:write' 'companyrecord' %} '"><button type="button">글쓰기</button></a>
</div>
</div>
{% endblock %}

post/templates/post/companyrecord/write.html
{% extends 'base.html' %}
{% block script %}
<script src = "/static/js/my.js"></script>
{% endblock %}

{% block content %}
<style>
    table {width:100%;}
    td {height:70px;}
    .c1, .c3, .c5 {
        width:140px;
        background-color: #EFFBFB;
        text-align: center;
     }
     .tb {margin-top:40px;}
     .errorlist {color:red;}

     .t2 input {width:130px;}

     ul > li {display:inline-block;}
     ul  {display:inline-block;}
</style>
<h3>수혜기업 이력관리 글쓰기</h3>
<form action="" method="post">
    {% csrf_token %}
    <div class="tb">
        <h5>업무처리 현황</h5>
        <table border="1" class="t1">
            <tr>

                <td class="c1">수혜기업명</td>
                <td class="c2"><input id="id_company_name" readonly>{{form.company}} <button type="button" onclick="search('Company', 'name')">검색</button></td>
            </tr>

            <tr>
                <td class="c1">사업자 유형</td>
                <td class="c2"><input id="id_business_type" readonly></td>
            </tr>

            <tr>
                <td class="c1">업무구분</td>
                <td class="c2">{{form.division}}</td>
            </tr>

            <tr>
                <td class="c1">처리방법</td>
                <td class="c2">{{form.process_method}} {{form.process_method_etc}}</td>
            </tr>

            <tr>
                <td class="c1">접수/발생 일시</td>
                <td class="c2">{{form.occurr_date}}</td>
            </tr>

            <tr>
                <td class="c1">업무처리 상태</td>
                <td class="c2">{{form.process_state}}</td>
            </tr>

        </table>
    </div>

    <div class="tb">
        <h5>담당자 등록정보</h5>
        <table border="1" class="t2">
            <tr>
                <td class="c1">{{form.visible_m}} {{form.visible_m.label_tag}}</td>
                <td class="c1">이름</td>
                <td class="c2"><input id="id_manager_m_name" readonly></td>
                <td class="c3">부서</td>
                <td class="c4"><input id="id_manager_m_depart" readonly></td>
                <td class="c5">휴대폰</td>
                <td class="c6"><input id="id_manager_m_phone" readonly></td>
                <td class="c7">회사전화</td>
                <td class="c8"><input id="id_manager_m_cphone" readonly></td>
                <td class="c9">E-mail</td>
                <td class="c10"><input id="id_manager_m_email" readonly></td>
            </tr>

            <tr>
                <td class="c1">{{form.visible_s}} {{form.visible_s.label_tag}}</td>
                <td class="c1">이름</td>
                <td class="c2"><input id="id_manager_s_name" readonly></td>
                <td class="c3">부서</td>
                <td class="c4"><input id="id_manager_s_depart" readonly></td>
                <td class="c5">휴대폰</td>
                <td class="c6"><input id="id_manager_s_phone" readonly></td>
                <td class="c7">회사전화</td>
                <td class="c8"><input id="id_manager_s_cphone" readonly></td>
                <td class="c9">E-mail</td>
                <td class="c10"><input id="id_manager_s_email" readonly></td>
            </tr>

            <tr>
                <td class="c1">{{form.visible_e}} {{form.visible_e.label_tag}}</td>
                <td class="c1">이름</td>
                <td class="c2">{{form.manager_e_name}}</td>
                <td class="c3">부서</td>
                <td class="c4">{{form.manager_e_depart}}</td>
                <td class="c5">휴대폰</td>
                <td class="c6">{{form.manager_e_phone}}</td>
                <td class="c7">회사전화</td>
                <td class="c8">{{form.manager_e_cphone}}</td>
                <td class="c9">E-mail</td>
                <td class="c10">{{form.manager_e_email}}</td>
            </tr>
        </table>
    </div>

    <div class="tb">
        <h5>업무 처리 내용 및 관련 사항</h5>
        <table border="1" class="t3">
            <tr>
                <td class="c1">제목</td>
                <td class="c2">{{form.title}}</td>
            </tr>
            <tr>
                <td class="c1">세부 내용</td>
                <td class="c2">{{form.content}}</td>
            </tr>
        </table>
    </div>

    <div class="tb">
        <button type="submit">작성완료</button>
        <input type=button value="취소" onClick="javascript:history.go(-1);">
    </div>
</form>
{{ form.errors }}
<script>
    window.onload = function(){
        //document.getElementById('id_company_name').value = '{{object.name}}';
        //document.getElementById('id_company_name').value = '{{object.name}}';
        {% if object %}
        url = '{% url 'post:select' 'Company' object.company.id %}';
        if(url)
            child = window.open(url, 'window팝업', 'width=400, height=400, menubar=no, status=no, toolbar=no');
        {% endif %}
        //alert('{{form.occurr_date.value}}');
    }


</script>
{% endblock %}