config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('post/', include('post.urls')),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('join', views.join, name='join'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('check/userid', views.check_userid, name='check_userid'),
    path('check/nickname', views.check_nickname, name='check_nickname'),
    path('confirm_password', views.confirmPassword, name='confirm_password'),
    path('update_user', views.updateUser, name='update_user'),
]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('<str:model>/write/', views.write, name='write'),
    path('<str:model>/update/<int:pk>/', views.update, name='update'),
    path('<str:model>/list/', views.list, name='list'),
    path('<str:model>/detail/<int:pk>/', views.detail, name='detail'),
    path('<str:model>/delete/<int:pk>/', views.delete, name='delete'),
    path('<str:model>/export/', views.export, name='export'),
    path('check/<str:model>/<str:field_name>/<str:ele_id>/', views.check, name='check'),
    path('search/<str:model>/<str:field_name>/', views.search, name='search'),
    path('select/<str:model>/<int:id>/', views.select, name='select'),

    path('<str:model>/<int:id>/answer/write/', views.writeAnswer, name='answer_write'),
    path('answer/detail/<int:pk>/', views.detail, name='answer_detail'),
    path('answer/update/<int:pk>/', views.detail, name='answer_update'),
    path('answer/delete/<int:pk>/', views.detail, name='answer_delete'),
]

post/all_forms/administration/forms.py
from django import forms
from post.models import Timetable, Notice, Takeover
from django_summernote.widgets import SummernoteWidget
from post.my_def import to_date_widget

class TimetableForm(forms.ModelForm):
    class Meta:
        model = Timetable
        exclude = ('user', 'views')
        widgets = {
            'content': SummernoteWidget,
        }

class NoticeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(NoticeForm, self).__init__(*args, **kwargs)
        to_date_widget(self.fields)

    class Meta:
        model = Notice
        exclude = ('user', 'views')
        widgets = {
            'content': SummernoteWidget,
        }

class TakeoverForm(forms.ModelForm):
    class Meta:
        model = Takeover
        exclude = ('user', 'views')
        widgets = {
            'content': SummernoteWidget,
        }

post/all_forms/calendar/forms.py
from django import forms
from post.models import Schedule, Attendance
from post.my_def import to_date_widget

class ScheduleForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ScheduleForm, self).__init__(*args, **kwargs)
        to_date_widget(self.fields)

    class Meta:
        model = Schedule
        exclude = ('user','views')

class AttendanceForm(forms.ModelForm):
    class Meta:
        model = Attendance
        exclude = ('user', )

post/all_views/administration/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect, reverse
from post.models import Timetable, Notice, Takeover, Comment
from post.all_forms.administration.forms import TimetableForm, NoticeForm, TakeoverForm
from post.my_def import set_default, get_objects_by_request_ex, set_session, get_side_obj, config_page_uri, view, delete_object
from django.core.paginator import Paginator
from django.conf import settings

PAGE = settings.OBJECTS_IN_PAGE

@login_required
def writeTimetable(request):
    if request.method == 'POST':
        form = TimetableForm(request.POST, request.FILES)
        if form.is_valid():
            ips_tune = form.save(commit=False)
            ips_tune.user = request.user
            ips_tune.save()

            return HttpResponseRedirect(reverse("post:list",args=['timetable']))
    else:
        form = TimetableForm()
    return render(request, 'post/timetable/write.html', {'form': form})

@login_required
def writeNotice(request):
    if request.method == 'POST':
        form = NoticeForm(request.POST, request.FILES)
        if form.is_valid():
            ips_tune = form.save(commit=False)
            ips_tune.user = request.user
            ips_tune.save()

            return HttpResponseRedirect(reverse("post:list",args=['notice']))
    else:
        form = NoticeForm()
    return render(request, 'post/notice/write.html', {'form': form})

@login_required
def writeTakeover(request):
    if request.method == 'POST':
        form = TakeoverForm(request.POST, request.FILES)
        if form.is_valid():
            ips_tune = form.save(commit=False)
            ips_tune.user = request.user
            ips_tune.save()

            return HttpResponseRedirect(reverse("post:list",args=['takeover']))
    else:
        form = TakeoverForm()
    return render(request, 'post/takeover/write.html', {'form': form})

@login_required
def updateTimetable(request, id):
    instance = Timetable.objects.get(id=id)
    if request.method == 'POST':
        form = TimetableForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("post:list",args=['timetable']))
    else:
        form = TimetableForm(instance=instance)
    return render(request, 'post/timetable/write.html', {'form':form})

@login_required
def updateNotice(request, id):
    instance =Notice.objects.get(id=id)
    if request.method == 'POST':
        form = NoticeForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("post:list",args=['notice']))
    else:
        form = NoticeForm(instance=instance)
    return render(request, 'post/notice/write.html', {'form':form})

@login_required
def updateTakeover(request, id):
    instance = Takeover.objects.get(id=id)
    if request.method == 'POST':
        form = TakeoverForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("post:list",args=['takeover']))
    else:
        form = TakeoverForm(instance=instance)
    return render(request, 'post/takeover/write.html', {'form':form})

def listTimetable(request):
    model = Timetable
    default_GET = '?reverse=false&order_by=-created&search_field=title&filter_option=__icontains&search_data=&search_data2=&relation=%26&page=1'

    if not request.GET:
        return set_default(model, request, default_GET)

    result = get_objects_by_request_ex(request, model, default_GET)
    if result['success']:
        objects, page = result['data']
    else:
        print(result['error'])
        return set_default(model, request, default_GET)

    set_session(request,objects,model)
    total = len(objects)
    paginator = Paginator(objects, PAGE)

    try:
        objects = paginator.page(page)
    except:
        objects = paginator.page(1)

    content = {
        'objects':objects,
        'total':total,
    }
    return render(request, 'post/timetable/list.html', content)

def listNotice(request):
    model = Notice
    default_GET = '?reverse=false&order_by=-created&search_field=title&filter_option=__icontains&search_data=&search_data2=&relation=%26&page=1'

    if not request.GET:
        return set_default(model, request, default_GET)

    result = get_objects_by_request_ex(request, model, default_GET)
    if result['success']:
        objects, page = result['data']
    else:
        print(result['error'])
        return set_default(model, request, default_GET)

    set_session(request,objects,model)
    total = len(objects)
    paginator = Paginator(objects, PAGE)

    try:
        objects = paginator.page(page)
    except:
        objects = paginator.page(1)

    content = {
        'objects':objects,
        'total':total,
    }
    return render(request, 'post/notice/list.html', content)

def listTakeover(request):
    model = Takeover
    default_GET = '?reverse=false&order_by=-created&search_field=title&filter_option=__icontains&search_data=&search_data2=&relation=%26&page=1'

    if not request.GET:
        return set_default(model, request, default_GET)

    result = get_objects_by_request_ex(request, model, default_GET)
    if result['success']:
        objects, page = result['data']
    else:
        print(result['error'])
        return set_default(model, request, default_GET)

    set_session(request,objects,model)
    total = len(objects)
    paginator = Paginator(objects, PAGE)

    try:
        objects = paginator.page(page)
    except:
        objects = paginator.page(1)

    content = {
        'objects':objects,
        'total':total,
    }
    return render(request, 'post/takeover/list.html', content)

def detailTimetable(request, id):
    model = Timetable

    object = model.objects.get(id=id)
    view(object)

    pre_obj, next_obj = get_side_obj(request, id, model=model.__name__)
    comment = Comment.objects.filter(model_name=model.__name__, model_pk=id)

    uri = reverse('post:list', args=[model.__name__])
    if request.session[settings.LIST_CONDITIONS_ID].get(model.__name__):
        uri = config_page_uri(request, id, model.__name__, PAGE)

    content = {
        'object':object,
        'pre_obj':pre_obj,
        'next_obj':next_obj,
        'comment':comment,
        'uri' : uri,
    }

    return render(request, 'post/timetable/detail.html', content)

def detailNotice(request, id):
    model = Notice

    object = model.objects.get(id=id)
    view(object)

    pre_obj, next_obj = get_side_obj(request, id, model=model.__name__)
    comment = Comment.objects.filter(model_name=model.__name__, model_pk=id)

    uri = reverse('post:list', args=[model.__name__])
    if request.session[settings.LIST_CONDITIONS_ID].get(model.__name__):
        uri = config_page_uri(request, id, model.__name__, PAGE)

    content = {
        'object':object,
        'pre_obj':pre_obj,
        'next_obj':next_obj,
        'comment':comment,
        'uri' : uri,
    }

    return render(request, 'post/notice/detail.html', content)

def detailTakeover(request, id):
    model = Takeover

    object = model.objects.get(id=id)
    view(object)

    pre_obj, next_obj = get_side_obj(request, id, model=model.__name__)
    comment = Comment.objects.filter(model_name=model.__name__, model_pk=id)

    uri = reverse('post:list', args=[model.__name__])
    if request.session[settings.LIST_CONDITIONS_ID].get(model.__name__):
        uri = config_page_uri(request, id, model.__name__, PAGE)

    content = {
        'object':object,
        'pre_obj':pre_obj,
        'next_obj':next_obj,
        'comment':comment,
        'uri' : uri,
    }

    return render(request, 'post/takeover/detail.html', content)


def deleteTimetable(request, id):
    delete_object(Timetable, id)
    return HttpResponseRedirect(reverse('post:list', args=['timetable']))

def deleteNotice(request, id):
    delete_object(Notice, id)
    return HttpResponseRedirect(reverse('post:list', args=['notice']))

def deleteTakeover(request, id):
    delete_object(Takeover, id)
    return HttpResponseRedirect(reverse('post:list', args=['takeover']))

post/all_views/calendar/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse, HttpResponse
import datetime, calendar
from post.models import Schedule, Attendance, Comment
from post.all_forms.calendar.forms import ScheduleForm, AttendanceForm
from django.contrib.auth.decorators import login_required
import datetime
from django.db.models import Q
from post.my_def import delete_object


@login_required
def writeSchedule(request):
    if request.method == 'POST':
        form = ScheduleForm(request.POST, request.FILES)
        if form.is_valid():
            obj =form.save(commit=False)
            obj.user = request.user
            obj.save()
            return HttpResponseRedirect(reverse("post:list",args=['calendar']))
    else:
        form = ScheduleForm()
    return render(request, 'post/calendar/write.html', {'form':form})

def deleteSchedule(request, id):
    delete_object(Schedule, id)
    return HttpResponseRedirect(reverse('post:list', args=['calendar']))

@login_required
def writeAttendance(request):
    today = datetime.datetime.today()
    success = False
    if request.method == 'POST':
        form = AttendanceForm(request.POST, request.FILES, label_suffix="")
        if form.is_valid():
            obj =form.save(commit=False)
            obj.user = request.user
            obj.save()
            success = today.strftime('%H:%M:%S')
    else:
        form = AttendanceForm(label_suffix="")
    return render(request, 'post/calendar/attendance_write.html', {'form':form, 'success':success})

@login_required
def updateSchedule(request, id):
    instance = Schedule.objects.get(id=id)
    if request.method == 'POST':
        form = ScheduleForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse(('post:list'), args=['calendar']))
    else:
        form = ScheduleForm(instance=instance)
    return render(request, 'post/calendar/write.html', {'form':form})

@login_required
def updateAttendance(request, id):
    today = datetime.datetime.today()
    success = False
    instance = Attendance.objects.get(id=id)
    if request.method == 'POST':
        form = AttendanceForm(request.POST, instance=instance, label_suffix="")
        if form.is_valid():
            form.save()
            success = today.strftime('%H:%M:%S')
    else:
        form = AttendanceForm(instance=instance, label_suffix="")
    return render(request, 'post/calendar/attendance_write.html', {'form':form, 'success':success})

def listCalendar(request):
    today = datetime.datetime.today()
    default_GET = '?year=%s&month=%s'%(today.year, today.month)

    if not request.GET:
        return set_default(default_GET)

    else:
        try:
            year = int(request.GET['year'])
            month = int(request.GET['month'])
            if month == 13:
                return set_default(('?year=%s&month=%s'%(year+1, 1)))
            if month == 0:
                return set_default(('?year=%s&month=%s'%(year-1, 12)))

        except:
            return set_default(default_GET)

        days = get_content_month(year,month)
        today = Schedule.get_today()
        return render(request, 'post/calendar/list.html', {'days': days, 'today': today})

def detailSchedule(request, id):
    model = Schedule

    object = model.objects.get(id=id)
    comment = Comment.objects.filter(model_name=model.__name__, model_pk=id)

    content = {
        'object': object,
        'comment': comment,
    }
    return render(request, 'post/calendar/detail.html', content)


def set_default(default_GET):
    redirect = reverse('post:list', args=['calendar']) + default_GET
    return HttpResponseRedirect(redirect)

def get_content_month(year, month):
    cal = calendar.Calendar(firstweekday=6)
    days = cal.monthdayscalendar(year, month)
    new_days = []
    for week in days:
        cur_week = []
        for day in week:
            if not day:
                schedule = None
                attendancd = None
            else:
                date = datetime.date(year, month, day)
                Q1 = Q(start_date__lte=date)
                Q2 = Q(end_date__gte=date)
                schedule = Schedule.objects.filter(Q1 & Q2).order_by('start_date')
                attendancd = Attendance.objects.filter(attendance_date=date)

            content = {'day':day , 'schedule': schedule, 'attendance': attendancd}
            cur_week.append(content)

        new_days.append(cur_week)

    return new_days

post/all_views/check/views.py
from django.shortcuts import render
from main.models import Company, User
from post.models import DetectionPattern

def check(request, model,field_name, ele_id):
    success = False
    verbose_name = eval("%s._meta.get_field('%s').verbose_name"%(model,field_name))
    confirm_data = ""
    if request.method == 'POST':
        confirm_data = request.POST['confirm_data']
        if not eval("%s.objects.filter(%s='%s')"%(model,field_name,confirm_data)):
            success = True
    content = {
        'verbose_name':verbose_name,
        'confirm_data':confirm_data,
        'success':success,
        'ele_id':ele_id,
    }
    return render(request, 'post/check/check.html', content)

post/all_views/search/views.py
from django.shortcuts import render
from main.models import Company


def search(request, model, field_name):
    objects = None
    verbose_name = eval("%s._meta.get_field('%s').verbose_name" % (model, field_name))
    if request.method == 'POST':
        objects = eval('%s.objects.filter(%s__icontains = request.POST["search_data"])'%(model, field_name))
    content = {
        'objects':objects,
        'verbose_name':verbose_name
    }
    template_name = model[0].lower() + model[1:]
    return render(request, 'post/search/%s.html'%template_name, content)

def select(request, model, id):
    object = eval('%s.objects.get(id=id)'%model)
    template_name = model[0].lower() + model[1:]
    return render(request, 'post/search/%s_select.html'%template_name, {'object':object})

post/templates/post/outflow/detail.html
{% extends 'base.html' %}

{% block content %}
<style>
    table {width:100%;}
    td {height:70px;}
    .c1, .c3, .c5 {
        width:140px;
        background-color: #EFFBFB;
        text-align: center;
     }
     .tb {margin-top:40px;}
     .btn_div *{margin:20px;}
     .btn_div {text-align:center;}
</style>
<h3>기술유출 상세</h3>


<div class="tb">
    <h5>통보 정보</h5>
    <table border="1">
        <tr>
            <td class="c1">기업명</td>
            <td class="c2">{{object.company.name}}</td>
            <td class="c3">문서번호</td>
            <td class="c4">{{object.document_n}}</td>
            <td class="c5">발송 날짜</td>
            <td class="c6">{{object.send_date}}</td>
        </tr>
        <tr>
            <td class="c1">URL</td>
            <td colspan="5">{{object.url}}</td>
        </tr>
        <tr>
            <td class="c1">발견 취약점</td>
            <td colspan="5">
                {% for w in object.weekness.all %}
                    {{w.value}},
                {% endfor %}
            </td>
        </tr>
        <tr>
            <td class="c1">처리상태</td>
            <td colspan="5">
                {{object.process_state}}
            </td>
        </tr>
    </table>
    <h5>권고 내용</h5>
    {{object.content|safe}}
</div>

<div class="tb">
<div class="btn_div">
    {% if pre_obj %}
    <a href="#" onclick="location.href = '{% url 'post:detail' 'outflow' pre_obj.id %}'"><button type="button">이전글</button></a>
    {% endif %}
    {% if next_obj %}
    <a href="#" onclick="location.href = '{% url 'post:detail' 'outflow' next_obj.id %}'"><button type="button">다음글</button></a>
    {% endif %}
    <a href="#" onclick="location.href = '{{uri}}'"><button type="button">목록으로</button></a>
    {% if request.user.id == object.user.id %}
    <a href="#" onclick="location.href = ' {% url 'post:update' 'outflow' object.id %} '"><button type="button">수정하기</button></a>
    <a href="#" onclick="location.href = ' {% url 'post:delete' 'outflow' object.id %} '"><button type="button">삭제</button></a>
    {% endif %}
    <a href="#" onclick="location.href = ' {% url 'post:write' 'outflow' %} '"><button type="button">글쓰기</button></a>
</div>
</div>
{% endblock %}

post/templates/post/outflow/list.html
{% extends 'base.html' %}
{% block style %}
<script src = "/static/js/my.js"></script>
<link rel="stylesheet" href="/static/js/mystyle.css">
{% endblock %}
{% block content %}
{% load post_extras %}
<style>
    table {width:100%;}
    table *{text-align:center;}
    thead {background-color:lightcyan;}
    td {height:50px;}
</style>
<div>
    <a href="{% url 'post:list' 'outflow'%}"><h3>기술유출</h3></a>
    <h5>*Total : {{total}}</h5>
    <a href="{% url 'post:list' 'outflow'%}">필터링초기화</a>
    <table class="t1">
        <thead>
        <tr>
            <td><a style="cursor:pointer" id="no" onclick="set_reverse()">번호&#9660;</a></td>
            <td><a style="cursor:pointer" id="send_date" onclick="set_search_field(this)" data-toggle="modal" data-target="#m_date">발송 날짜&#9660;</a></td>
            <td><a style="cursor:pointer" id="document_n" onclick="set_search_field(this)" data-toggle="modal" data-target="#m_text">문서번호&#9660;</a> </td>
            <td><a style="cursor:pointer" id="company__name" onclick="set_search_field(this)" data-toggle="modal" data-target="#m_text">기업명&#9660;</a> </td>
            <td><a style="cursor:pointer" id="weekness" onclick="set_search_field(this)" data-toggle="modal" data-target="#m_only">발견 취약점&#9660;</a></td>
            <td><a style="cursor:pointer" id="process_state" onclick="set_search_field(this)" data-toggle="modal" data-target="#m_text">처리상태&#9660;</a></td>
        </tr>
        </thead>
        <tbody>
        {% for object in objects %}
            <tr>
                <td>
                    {% if request.GET.reverse == 'false' %}
                    {{total | sub:forloop.counter0 | sub:objects.start_index | add:1}}
                    {% else %}
                    {{forloop.counter0|add:objects.start_index}}
                    {% endif %}
                </td>
                <td><a href="#" onclick="location.href ='{% url 'post:detail' 'outflow' object.id %}'">{{object.send_date}}</a></td>
                <td>{{object.document_n}}</td>
                <td> {{object.company.name}}</td>
                <td>{{object.get_weekness_as_text}}</td>
                <td>{{object.process_state}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<a href="#" onclick="location.href = '{% url 'post:write' 'outflow' %}'"><button type="button">글쓰기</button></a>
<a href="#" onclick="location.href = '{% url 'post:export' 'outflow' %}?order_by={{request.GET.order_by}}'"><button type="button">Excel로 다운로드</button></a>

<div>
{% if objects.has_other_pages %}
  <ul class="pagination">
    {% if objects.has_previous %}
      <li class="page-item"><a class="page-link" onclick="set_page({{objects.previous_page_number}})">처음</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link"><span>처음</span></a></li>
    {% endif %}
    {% for i in objects.paginator.page_range %}
      {% if objects.number == i %}
        <li class="page-item active "><a class="page-link"><span>{{ i }} <span class="sr-only">(current)</span></span></a></li>
      {% else %}
        <li class="page-item"><a class="page-link" onclick="set_page({{i}})">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if objects.has_next %}
      <li class="page-item"><a class="page-link" onclick="set_page({{objects.next_page_number}})">맨끝</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link"><span>맨끝</span></a></li>
    {% endif %}
  </ul>
{% endif %}
</div>

<div>
    <form id="condition" action="" method="get">
        <input type="hidden" id="reverse" name="reverse" value="false">
        <input type="hidden" id="order_by" name="order_by" value="send_date">
        <input type="hidden" id="filter_option" name="filter_option" value="__icontains">
        <input type="hidden" id="relation" name="relation" value="&">
        <input type="hidden" id="search_field" name="search_field" value="company">
        <input type="hidden" id="search_data" name="search_data" value="">
        <input type="hidden" id="search_data2" name="search_data2" value="">
        <input type="hidden" id="page" name="page" value="1">
    </form>
</div>

{% include 'post/modal/textFilter.html'  %}
{% include 'post/modal/dateFilter.html'  %}
{% include 'post/modal/onlyFilter.html'  %}
<script>
    var form = document.getElementById('condition');
    var search_field = '';
    window.onload = function(){
        //set_btn_inner();
        set_request_get();
    }

    function set_btn_inner(){
        order_by = '{{request.GET.order_by}}';
        is_down = order_by[0] == "-";
        if(is_down)
            order_by = order_by.substr(1);
        ele = document.getElementById(order_by);
        inner = ele.innerHTML;
        inner = inner.substr(0, inner.length-1);
        if(is_down)
            ele.innerHTML = inner + '▼';
        else
            ele.innerHTML = inner + '▲';
    }

    function set_order_by(ele){
        document.getElementById('order_by').value = get_btn_value(ele);
        form.submit();
    }
    function set_page(i){
        document.getElementById('page').value = i;
        form.submit();
    }

    function set_request_get(){
        {% for key, val in request.GET.items %}
            document.getElementById('{{key}}').value = '{{val|safe}}';
        {% endfor %}
    }

    function set_search_field(ele){
        search_field = ele.id;
    }


</script>
{% endblock %}

post/templates/post/outflow/write.html
{% extends 'base.html' %}
{% block script %}
<script src = "/static/js/my.js"></script>
{% endblock %}

{% block content %}
<style>
    table {width:100%;}
    td {height:70px;}
    .c1, .c3, .c5 {
        width:140px;
        background-color: #EFFBFB;
        text-align: center;
     }
     .tb {margin-top:40px;}
     .errorlist {color:red;}
</style>
<h3>기술유출 글쓰기</h3>
<form action="" method="post">
    {% csrf_token %}
    <div class="tb">
        <h5>통보 정보</h5>
        <table border="1">
            <tr>
                <td class="c1">기업명</td>
                <td class="c2"><input id="id_company_name" readonly>{{form.company}} <button type="button" onclick="search('Company', 'name')">검색</button></td>
                <td class="c3">문서번호</td>
                <td class="c4">{{form.document_n}}</td>
                <td class="c5">발송 날짜</td>
                <td class="c6">{{form.send_date}}</td>
            </tr>
            <tr>
                <td class="c1">URL</td>
                <td colspan="5">{{form.url}}</td>
            </tr>
            <tr>
                <td class="c1">발견 취약점</td>
                <td colspan="5">
                    {{form.weekness1}}{{form.weekness1.label_tag}} {{form.weekness2}}{{form.weekness2.label_tag}} {{form.weekness3}}{{form.weekness3.label_tag}} {{form.weekness4}}{{form.weekness4.label_tag}}
                    {{form.weekness5}}{{form.weekness5.label_tag}} {{form.weekness6}}{{form.weekness6.label_tag}}<br> {{form.weekness7}}{{form.weekness7.label_tag}} {{form.weekness8}}{{form.weekness8.label_tag}}
                    {{form.weekness9}}{{form.weekness9.label_tag}} {{form.weekness10}}{{form.weekness10.label_tag}} {{form.weekness11}}{{form.weekness11.label_tag}} {{form.weekness12}}{{form.weekness12.label_tag}}
                </td>
            </tr>
            <tr>
                <td class="c1">처리상태</td>
                <td colspan="5">
                    {{form.process_state}}
                </td>
            </tr>
        </table>
        <h5>권고 내용</h5>{{form.content.errors}}
        {{form.content|safe}}
    </div>

    <div class="tb">
        <button type="submit">작성완료</button>
        <input type=button value="취소" onClick="javascript:history.go(-1);">
    </div>
</form>
<script>
    window.onload = function(){
        {% for w in weekness %}
            document.getElementById('id_{{w.widget_id}}').setAttribute('checked', 'true');
        {% endfor %}

        if(!document.getElementById('id_process_state').value)
            document.getElementById('id_process_state').value = '처리중';

        {% if object %}
        url = '{% url 'post:select' 'Company' object.company.id %}';
        if(url)
            child = window.open(url, 'window팝업', 'width=400, height=400, menubar=no, status=no, toolbar=no');
        {% endif %}
    }

    function set_process_state(ele){
        if(ele.value)
            document.getElementById('id_process_state').value = '처리완료';
        else
            document.getElementById('id_process_state').value = '처리중';
    }
</script>
{% endblock %}